### ISSUE TITLE
Feature: Support for multiple Plex servers/instances

### ISSUE THREAD

**Issue by owine** [cjmanca/plex-credits-detect#19]
Would be great to have one instance of PCD support multiple Plex instances for people who run multiple/backup servers. I use Docker so I am thinking of an ability to define in the ini the path to additional databases which are mounted into the container at unique paths.

**Comment by cjmanca** [comment]
Hmm, interesting. So all the same files are being served by all the plex servers?

**Comment by owine** [comment]
Not necessarily - each Plex instance may serve a different selection of files.

**Comment by cjmanca** [comment]
Then I'd think it would be best to just run a separate instance of PCD for each server. I don't really see a benefit to trying to handle multiple from one instance if they aren't sharing files. It just increases complexity (and the potential for issues)
