### ISSUE TITLE
I don't understand how it works

### ISSUE THREAD

**Issue by Write** [cjmanca/plex-credits-detect#23]
Hello,

I'm struggling to make this work.
It doesn't scan any media.
It just says 

```
plex-credits-detect    | Syncing newly added episodes from plex...
plex-credits-detect    |
plex-credits-detect    | Found changed directories: 0
```

I'm quite sure everything is okay, media directory is mounted as /data both for plex and plex-credits-detect.
`docker exec -it plex-credits-detect /bin/sh` shows that /data is correctly mounted and not empty.

I've added subdir for Movies / Shows in [directories] just to be sure, but nothing is changed
/PlexDB is also correctly mounted.

I can confirm that the .ini is correctly read by the app, because I misstyped a directory once and it showed up in the console.

Here's my .ini

```
[directories]
/data = /data
/data/Films = /data/Films
/data/Films4k = /data/Films4k
/data/Séries = /data/Séries
/data/Séries4k = /data/Séries4k

[intro]
introStart = 0
introEnd = 0.5
introMaxSearchPeriod = 900

[credits]
creditsStart = 0.75
creditsEnd = 1.0
creditsMaxSearchPeriod = 600

[matching]
useAudio = true
useVideo = false
introMatchCount = 0
creditsMatchCount = 1
quickDetectFingerprintSamples = 5
fullDetectFingerprintMaxSamples = 10
audioAccuracy = 4
stride = 512
sampleRate = 5512
minFrequency = 100
maxFrequency = 2750
videoAccuracy = 2
videoSizeDivisor = 50
frameRate = 1

[silence]
detectSilenceAfterCredits = true
silenceDecibels = -55

[blackframes]
detectBlackframes = true
blackframeOnlyMovies = true
blackframeUseMaxSearchPeriodForEpisodes = true
blackframeUseMaxSearchPeriodForMovies = false
blackframeScreenPercentage = 75
blackframePixelPercentage = 2
blackframeMovieMinimumMatchSeconds = 20

[timing]
shiftSegmentBySeconds = 2
minimumMatchSeconds = 20
PermittedGap = 3
PermittedGapWithMinimumEnclosure = 10

[redetection]
crawlDirectoriesOnStartup = false
recheckBlackframesOnStartup = false
recheckSilenceOnStartup = false
recheckUndetectedOnStartup = false
forceRedetect = false
redetectIfFileSizeChanges = true

[paths]
databasePath = /config/plex-credits-detect/database
PlexDatabasePath = /PlexDB/com.plexapp.plugins.library.db
TempDirectoryPath = /config/plex-credits-detect/temp
ffmpegPath = ffmpeg

[monitoring]
monitorPlexIntros = True
monitorDirectoryChanges = True
```

**Comment by cjmanca** [comment]
I'd suggest deleting the local database (in /config/plex-credits-detect/database, based on your config) and trying again. It's possible that an earlier attempt with incorrect path mapping worked it's way through the whole library unsuccessfully and as a result, it marked all directory changes as processed.

(There are alternate ways to handle this with the redetection variables if you had a working DB already, but since this is first run, it's easier just to delete the database and start over)

**Comment by Write** [comment]
That indeed fixed it, thank you !
