### ISSUE TITLE
Not detecting changed directories

### ISSUE THREAD

**Issue by micahmo** [cjmanca/plex-credits-detect#30]
Hi @cjmanca!

First of all I want to say that this is an amazing tool! Thanks for all your work on this!

I believe I've discovered a bit of a bug related to change detection. After the initial processing, I have been adding media, but plex-credits-detect has not been detecting it. It only detects after a restart of the application. I did some troubleshooting and I found that the Plex database query was returning incorrectly.

I opened the db open in DB Browser, and you can see there is a changed directory at 9:16.

| ![image](https://user-images.githubusercontent.com/7417301/184911505-8409672b-0a66-469d-a44e-7ecc670d5d29.png) |
| - |

However, in the code, it's returning no rows after 8:55.

| ![image](https://user-images.githubusercontent.com/7417301/184911684-09b02e26-d912-4ba5-83c9-6e866373dfb2.png) |
| - |

I even tweaked the code a bit to return all rows from the `directories` table, and `result.Get<DateTime>("updated_at")` still showed the old date.

I'm not sure if this is related to the fact that Plex seems to be using SQLite in WAL mode. But I tried creating the connection with `sb.JournalMode = SQLiteJournalModeEnum.Wal` and that didn't help.

| ![image](https://user-images.githubusercontent.com/7417301/184911778-5276bc1e-f016-46eb-9634-434704b1ebf9.png) |
| - |

The only thing that fixed this issue for me was closing and reopening the connection at the beginning of `GetRecentlyModifiedDirectories`. I suppose it's not the worst solution in the world since it happens at most 1/minute, but it doesn't seem right. If you have more experience with SQLite, may you'll have some idea why the queries seem to be returning stale data!

**Comment by cjmanca** [comment]
Seems to be working fine right now on my current working version. I just tested as follows:
1) Launched PCD
2) Renamed a video
3) "Scan Library Files" in Plex
4) Waited for ~60 seconds until PCD did it's next check

PCD correctly saw the changed directory and scanned it.

That said - I've been doing some fairly extensive database changes on my current working version, so it's possible I already accidentally fixed a bug that may have been causing it. You could grab the "in-progress" branch if you'd like to see if it's helped before the next release.

**Comment by cjmanca** [comment]
Yes, my Plex DB also has the shm/wal files. The Plex DB is configured in "write ahead log" mode (WAL), which I believe is a persistent database setting, and should be detected by connecting applications. That said - I'll change my connection string to explicitly use the WAL journal mode to be safe.

I suspect what may have solved it was properly closing query result connections. In researching some of the database locking issues, I found that apparently result connections must be explicitly closed, which I didn't realize before. It's possible that the unclosed previous results were interfering with subsequent queries.

**Comment by cjmanca** [comment]
Fixed by #34
