### ISSUE TITLE
Unable to start container - `Invalid database path`

### ISSUE THREAD

**Issue by oOOOoOoOoOOoOOOooooOOoff** [cjmanca/plex-credits-detect#32]
Hi, running the docker container (on a linux machine) for the first time with an initial `fingerprint.ini` file (just removed the mapping directory path)

**Log:** 
```
Loading global config file: /config/plex-credits-detect/fingerprint.ini
PlexDB.LoadDatabase - Invalid database path
Unhandled exception. System.ArgumentException: Invalid database path
  at plexCreditsDetect.Database.PlexDB.LoadDatabase(String path) in /src/plex-credits-detect/Database/PlexDB.cs:line 69
  at plexCreditsDetect.Program.Main(String[] args) in /src/plex-credits-detect/Program.cs:line 31
```
**fingerprint.ini**
```
[directories]

[intro]
introStart = 0
introEnd = 0.5
introMaxSearchPeriod = 900

[...]

[paths]
databasePath = /config/plex-credits-detect/database
PlexDatabasePath = /PlexDB/com.plexapp.plugins.library.db
TempDirectoryPath = /config/plex-credits-detect/temp
ffmpegPath = ffmpeg
```

**Docker command:** 
```
docker run \
	-d \
	--restart=always \
	-v $DATADIR/config:/config \
	-v '/mnt/SSD2/PlexMetas/Plug-in Support/Databases':/PlexDB \
	-v /media:/media:ro \
	--name $NAME \
	$IMAGE
```

Any thoughts?
Thx!

**Comment by cjmanca** [comment]
It can't access the com.plexapp.plugins.library.db. The two most likely possibilities are:
1. It doesn't have appropriate read/write permissions to that file
2. The file isn't actually located at the path: `/mnt/SSD2/PlexMetas/Plug-in Support/Databases/com.plexapp.plugins.library.db`

**Comment by oOOOoOoOoOOoOOOooooOOoff** [comment]
That was it, I thought this message was related to the internal database of plex-credits located next to the config (fingerprintmedia.db).

Thank you 👍
