### ISSUE TITLE
delete the credit based skips

### ISSUE THREAD

**Issue by JohnFawkes** [cjmanca/plex-credits-detect#33]
Is there currently a way to delete only the credit skip buttons this tool creates?

**Comment by cjmanca** [comment]
Not built into the tool, but it can be done a couple of ways:
1. If you'd like to remove from a few specific seasons, you could get plex re-detect intros. Plex removes all markers for the season when it does it's intro detection, including the ones generated by this tool. If my tool is running, it normally just re-inserts the previously detected credit markers immediately after, so to prevent it re-adding you'd want to add a fingerprint.ini file to that season with the detections all turned off.
2. If you'd like to remove _all_ credit markers from _all_ seasons/movies, you could use this sql:
```
DELETE FROM taggings WHERE `index` > 0 AND tag_id = (SELECT id FROM tags WHERE tag_type = 12);
 ```

**Comment by JohnFawkes** [comment]
I only did it for movies and i dont want to touch the tv shows that plex has created

**Comment by cjmanca** [comment]
All plex created intros have an `index` of 0. That SQL statement specifically ignores the plex created intros ( `WHERE index > 0` )

**Comment by PoloDePoli** [comment]
Where would one use the command  `DELETE FROM taggings WHERE `index` > 0 AND tag_id = (SELECT id FROM tags WHERE tag_type = 12);`?
When running plex from docker is that something to just be typed in the console?
