### ISSUE TITLE
Semantic versioning for container image releases

### ISSUE THREAD

**Issue by Infray** [cjmanca/plex-credits-detect#39]
Hi

Would it be possible to provide semantic version releases  for the container images?
I'm currently running the "main" container image, but have no idea which version this represents nor is it visible when this is updated.

Thanks for the big improvement to my plex life!

**Comment by cjmanca** [comment]
I've already started to do so. Older versions aren't there at the moment, but going forward all future versions will be accessible by version number:
https://hub.docker.com/repository/docker/cjmanca/plex-credits-detect/tags

**Comment by Infray** [comment]
For some reason if I want to open the page you provided ,it requires authentication.
I did see "in-progress-<version>" tags the regular page.
https://hub.docker.com/r/cjmanca/plex-credits-detect/tags

Thanks for providing this for the next releases.
I'll close the ticket then.

**Comment by cjmanca** [comment]
I guess the link I gave is a management link. I thought it was just a generic viewing link, sorry about that. Updated to the generic one.
