### ISSUE TITLE
[directories] path doesn't exist: d1

### ISSUE THREAD

**Issue by shinrkaurisu** [cjmanca/plex-credits-detect#4]
### Problem

The generated config/fingerprint.ini from version 1.0.4 uses the path format from 1.0.1 instead of the new format found in the README.md

Changing `d1 = C:\path\to\library` to a user-defined path like `d1 = C:\Users\test\Videos` presents this error:

[directories] path doesn't exist: d1

### Solution

1.0.4 requires the path to be listed as the following:

`C:\path\to\library = C:\path\to\library`

or in my case

`C:\Users\test\Videos = C:\Users\test\Videos`

Thank you for this amazing tool!

**Comment by cjmanca** [comment]
Oh, thanks for pointing that out! I guess I forgot to change the default generated version
