### ISSUE TITLE
What format is the ini file?

### ISSUE THREAD

**Issue by joeblack2k** [cjmanca/plex-credits-detect#8]
It's al garbled in nano or vi and MacOS textedit saves it corrupted

https://imgur.com/a/SpXc7pE

**Comment by cjmanca** [comment]
It defaults to unicode UTF-16 to support international character sets. If you don't want to use a unicode enabled editor, you could copy the one from the main github page and edit that.

**Comment by joeblack2k** [comment]
Hmm doesnt seem to work

`Unhandled exception. IniParser.Exceptions.ParsingException: Unknown file format. Couldn't parse the line: '# Place as many of these entries as you'd like for your plex libraries.'. while parsing line number 0 with value '' - IniParser version: 2.5.2.0 while parsing line number 4 with value '# Place as many of these entries as you'd like for your plex libraries. ' - IniParser version: 2.5.2.0
 ---> IniParser.Exceptions.ParsingException: Unknown file format. Couldn't parse the line: '# Place as many of these entries as you'd like for your plex libraries.'. while parsing line number 0 with value '' - IniParser version: 2.5.2.0
`

i just did 

touch fingerprint.ini
nano fingerprint.ini 
paste 
save

**Comment by cjmanca** [comment]
Oh, sounds like the ini library I'm using doesn't understand comments then. The  version it generates doesn't have the documentation comments in it. Here, use this one:
```
[directories]
C:\path\this\tool\sees\to\library = C:\path\Plex\sees\to\library

[default]
useAudio = true
useVideo = false

introMatchCount = 0
creditsMatchCount = 1

introStart = 0
introEnd = 0.5
introMaxSearchPeriod = 900

creditsStart = 0.7
creditsEnd = 1.0
creditsMaxSearchPeriod = 600

shiftSegmentBySeconds = 2

minimumMatchSeconds = 20
PermittedGap = 3
PermittedGapWithMinimumEnclosure = 10

audioAccuracy = 4
stride = 1024
sampleRate = 5512
minFrequency = 100
maxFrequency = 2750

videoAccuracy = 2
videoSizeDivisor = 50
frameRate = 1

recheckUndetectedOnStartup = false
forceRedetect = false

databasePath = C:\path\to\database\dir
PlexDatabasePath = C:\path\to\com.plexapp.plugins.library.db
ffmpegPath = ffmpeg
TempDirectoryPath = C:\path\to\empty\temp\dir
```

**Comment by joeblack2k** [comment]
There we go!

Scanning as we speak

Thanks!
